# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persistent_properties.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='persistent_properties.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x1bpersistent_properties.proto\"\x93\x01\n\x14PersistentProperties\x12\x42\n\nproperties\x18\x01 \x03(\x0b\x32..PersistentProperties.PersistentPropertyRecord\x1a\x37\n\x18PersistentPropertyRecord\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB\x02H\x03')
)




_PERSISTENTPROPERTIES_PERSISTENTPROPERTYRECORD = _descriptor.Descriptor(
  name='PersistentPropertyRecord',
  full_name='PersistentProperties.PersistentPropertyRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PersistentProperties.PersistentPropertyRecord.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PersistentProperties.PersistentPropertyRecord.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=179,
)

_PERSISTENTPROPERTIES = _descriptor.Descriptor(
  name='PersistentProperties',
  full_name='PersistentProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='properties', full_name='PersistentProperties.properties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSISTENTPROPERTIES_PERSISTENTPROPERTYRECORD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=179,
)

_PERSISTENTPROPERTIES_PERSISTENTPROPERTYRECORD.containing_type = _PERSISTENTPROPERTIES
_PERSISTENTPROPERTIES.fields_by_name['properties'].message_type = _PERSISTENTPROPERTIES_PERSISTENTPROPERTYRECORD
DESCRIPTOR.message_types_by_name['PersistentProperties'] = _PERSISTENTPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersistentProperties = _reflection.GeneratedProtocolMessageType('PersistentProperties', (_message.Message,), dict(

  PersistentPropertyRecord = _reflection.GeneratedProtocolMessageType('PersistentPropertyRecord', (_message.Message,), dict(
    DESCRIPTOR = _PERSISTENTPROPERTIES_PERSISTENTPROPERTYRECORD,
    __module__ = 'persistent_properties_pb2'
    # @@protoc_insertion_point(class_scope:PersistentProperties.PersistentPropertyRecord)
    ))
  ,
  DESCRIPTOR = _PERSISTENTPROPERTIES,
  __module__ = 'persistent_properties_pb2'
  # @@protoc_insertion_point(class_scope:PersistentProperties)
  ))
_sym_db.RegisterMessage(PersistentProperties)
_sym_db.RegisterMessage(PersistentProperties.PersistentPropertyRecord)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
